{"name": "test_all_metadata", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestMetadata' object has no attribute 'hasattr'", "trace": "self = <case.anly.test_metadata.TestMetadata object at 0x04251670>\n\n    @pytest.fixture(scope='function', autouse=True)\n    def init_context(self):\n>       if self.hasattr('context'):\nE       AttributeError: 'TestMetadata' object has no attribute 'hasattr'\n\n..\\base.py:25: AttributeError"}, "uuid": "bac36433-5c64-49cd-84eb-5919c29327d9", "historyId": "cbc10bea9d93e65c3ac4dadc1594995d", "fullName": "case.anly.test_metadata.TestMetadata#test_all_metadata", "labels": [{"name": "host", "value": "PVGN56588630A"}, {"name": "thread", "value": "7640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.anly.test_metadata"}]}